# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tools/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tools/service.proto\x12\x0e\x65xtractservice\"\x1d\n\x0e\x45xtractRequest\x12\x0b\n\x03url\x18\x01 \x03(\t\"F\n\x10\x45xtractResponses\x12\x32\n\tresponses\x18\x01 \x03(\x0b\x32\x1f.extractservice.ExtractResponse\"M\n\x0f\x45xtractResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08sitename\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t2]\n\x0e\x45xtractService\x12K\n\x07\x45xtract\x12\x1e.extractservice.ExtractRequest\x1a .extractservice.ExtractResponsesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTREQUEST']._serialized_start=39
  _globals['_EXTRACTREQUEST']._serialized_end=68
  _globals['_EXTRACTRESPONSES']._serialized_start=70
  _globals['_EXTRACTRESPONSES']._serialized_end=140
  _globals['_EXTRACTRESPONSE']._serialized_start=142
  _globals['_EXTRACTRESPONSE']._serialized_end=219
  _globals['_EXTRACTSERVICE']._serialized_start=221
  _globals['_EXTRACTSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
