# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tools import service_pb2 as tools_dot_service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tools/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtractServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/extractservice.ExtractService/Extract',
                request_serializer=tools_dot_service__pb2.ExtractRequest.SerializeToString,
                response_deserializer=tools_dot_service__pb2.ExtractResponses.FromString,
                _registered_method=True)


class ExtractServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Extract(self, request, context):
        """Метод extract принимает запрос с URL и возвращает ответ с результатом.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=tools_dot_service__pb2.ExtractRequest.FromString,
                    response_serializer=tools_dot_service__pb2.ExtractResponses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'extractservice.ExtractService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('extractservice.ExtractService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtractService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/extractservice.ExtractService/Extract',
            tools_dot_service__pb2.ExtractRequest.SerializeToString,
            tools_dot_service__pb2.ExtractResponses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
